services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["fastapi", "run", "knight/api/app.py"]
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      [
        "celery",
        "-A",
        "knight.worker.celery_app:celery_app",
        "worker",
        "--loglevel=info",
        "--queues=knight.default",
      ]
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
